"""Span parity probe (#309): conformed spans vs. canonical assignments.

    python -m usa_wa_pipeline.parity_spans [--root PATH] [--baseline N]
                                          [--role-baseline N] [--json]

Write-free. Rebuilds the conformed spans from the raw store + the curated
operator events and diffs them against ``canonical.assignments`` for all four
kinds this tier owns (:data:`OWNED_KINDS` — ``party``, ``chamber-senate``,
``committee`` and, since #309 increment 3, ``chamber-house``), keyed on the
span's 4-part identity with ``valid_from``/``valid_to``/``is_active`` compared
exactly.

It also diffs the **role dimension** those spans name against
``canonical.roles`` (CR 77) — on the key *and* on :data:`ROLE_ATTRIBUTES`
(CR 84), because the one production instance of this fork (#110) changed no key
at all. The dbt ``assignments_name_a_role`` test cannot do either: ``roles`` is
generated by iterating ``assignments`` through the same ``role_for_span``, so
containment holds by construction and the query is unfalsifiable. The fork worth
detecting is ours drifting from the tier that already publishes these keys to
Power Map, and only a probe with a session can see it.

Both families are rebuilt and diffed: the WSL archive's (numeric member ids)
and the roster PDF's (minted ``<fold>:<year>`` identities). They share the
table but not the identity space, so the comparison key is
``(source, source_id)``.

**The oracle is a snapshot, and it is stale.** Measured 2026-09-03: the stored
assignments diverge from the port by :data:`BASELINE_DIVERGENCE` rows — and
running the *Postgres-tier adapter's own pipeline* fresh that day produced the
**identical** divergence for the WSL family (4,851 spans; 42 missing / 2 extra
/ 1 dated differently), because the stored rows predate the current
identity-resolve (the #277/#281 candidate-splitting work).

The roster family adds **37 missing rows across 15 identities, the same story
seen from the other side**: each is an identity the stored snapshot minted as a
roster person and today's resolve JOINS to a WSL member. Cliff Bailey is the
worked example — canonical holds both a shallow ``15:*:1991-92`` pair *and* a
minted ``cliffbailey:1985:*`` pair, where this build asserts the one merged
``15:*:1985-86`` tenure the #228 deepening produces. Nothing is lost; the
tenure moved families, which is exactly what the #97 collapse is for.

So this probe's gate is a **ratchet, not equality**: divergence at or below the
recorded baseline is the known staleness, and any growth is a regression in
the port. A Postgres-tier span rebuild would drop the baseline to zero, at
which point lower it here — the number dying is the point.

The counters in :data:`INTEGRITY_COUNTERS` carry no known-stale story and must
be ZERO; unlike the divergence ratchets they are gated, because the nightly
alerts on the exit code and a counter that only reaches journald tells nobody
(CR 72/73/78/84). A failing run names what tripped in ``integrity_failures``
and, for the two baselined counters, in ``ratchet_failures`` (CR 89).

Exit ``0`` clean · ``1`` either divergence past its baseline OR any integrity
counter nonzero · ``4`` degraded — no WSL store, no roster store or roster rows
(the #228 deepening's input, whose absence would read as a port regression), or
an empty oracle on either side. A degraded probe compared nothing and says so —
except an empty *role* oracle, which still reports the span diff it had already
finished (CR 85).
"""

from __future__ import annotations

import argparse
import os
from collections.abc import Callable
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from clearinghouse_core.job import JobContext, JobResult, run_job
from clearinghouse_core.logging import get_logger
from clearinghouse_core.rawstore import RawStore, get_raw_root
from clearinghouse_core.registry import KIND_ORG, KIND_PERSON
from clearinghouse_domain_legislative.identity import Assignment
from clearinghouse_domain_legislative.identity import Role as CanonicalRole
from clearinghouse_domain_legislative.terms import biennium_for_date
from usa_wa_pipeline.conformed.roles import SOURCE as ROLE_SOURCE
from usa_wa_pipeline.conformed.roles import role_rows
from usa_wa_pipeline.conformed.spans import (
    ROSTER_SOURCE,
    SOURCE,
    SpanInputs,
    assignment_rows,
    build_all_spans,
    build_roster_spans,
    entity_index,
    roster_records,
    roster_resolution,
)
from usa_wa_pipeline.operator_read import operator_event_rows
from usa_wa_pipeline.registry_read import crosswalk_rows
from usa_wa_pipeline.staging import roster as roster_staging
from usa_wa_pipeline.staging import sos as sos_staging
from usa_wa_pipeline.staging import wsl

logger = get_logger(__name__)

#: Stable ledger identity (#178).
JOB_SLUG = "parity-spans"

#: The SOS legislative-results store — the ballot that positions a House seat.
SOS_SOURCE = "usa_wa_sos_results"

#: Every span kind the conformed tier owns — all four since #309 increment 3
#: brought `chamber-house` (the WSL roster x SOS ballot join).
OWNED_KINDS = ("party", "chamber-senate", "committee", "chamber-house")

#: Known stale-oracle rows, measured 2026-09-03 (see the module docstring):
#: 42 + 37 missing (WSL shallow keys and their roster-minted twins, one
#: pre-#277 identity split each), 2 extra, 1 dated. Lower this the moment a
#: Postgres-tier rebuild lands — the number dying is the point.
BASELINE_DIVERGENCE = 82

#: The role dimension's own ratchet, measured 2026-09-03: **0** — 312 conformed
#: role keys against 312 in ``canonical.roles``, exact in both directions, with
#: matching ``role_type``s. Roles are far coarser than tenures (312 slots vs
#: 8,849 spans), so the pre-#277 identity splits that make
#: :data:`BASELINE_DIVERGENCE` nonzero do not change *which slots exist*. It is
#: a ratchet rather than an invariant for the same reason the span one is — the
#: oracle is a snapshot — but it starts where that one is going.
ROLE_BASELINE_DIVERGENCE = 0

#: The role attributes compared alongside the key, all derived HERE
#: independently of the tier that publishes them (CR 84). ``role_type`` is the
#: one with an incident: #110 churned 305 party roles on local ``member`` vs
#: PM's ``party_member`` — a fork in which every key stayed identical, so a
#: key-only diff sees nothing. Measured 2026-09-03: 0 mismatches on all three
#: across 312 roles, hence gated rather than ratcheted. Each name must be both
#: a key of a ``conformed.roles`` row and a column of ``canonical.roles``.
ROLE_ATTRIBUTES = ("role_type", "name", "qualifier")

#: Counters that must be ZERO, checked together (CR 72/73/78/84). Unlike the
#: divergence ratchets these carry no known-stale story — each is a defect in an
#: input or in the identity join, and each is 0 on the live corpus today. They
#: are *gated*, not merely reported, because the nightly's ``OnFailure=``
#: alerting fires on the exit code: a counter that only reaches journald tells
#: nobody, which is the silence findings 60 and 68 were about.
INTEGRITY_COUNTERS = (
    "unregistered_spans",
    "unregistered_orgs",
    "malformed_roster_rows",
    "unparsable_canonical_keys",
    "role_attribute_mismatches",
)


def _add_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--root", default=None, help="Raw store root (default USA_WA_RAW_ROOT).")
    parser.add_argument(
        "--baseline",
        type=int,
        default=BASELINE_DIVERGENCE,
        help="Max tolerated divergence from the (stale) canonical snapshot.",
    )
    parser.add_argument(
        "--role-baseline",
        type=int,
        default=ROLE_BASELINE_DIVERGENCE,
        help="Max tolerated divergence between the derived role keys and canonical.roles.",
    )


def owned_kind(source_id: str) -> str | None:
    """The span ``kind`` encoded in an assignment's ``source_id``, or ``None``.

    A span key is ``<member_id>:<kind>:<discriminator>:<start_biennium>`` — but
    the **member id is not colon-free**: the roster family mints ``<fold>:<year>``
    ids, so its keys carry five segments and counting from the left lands on the
    mint year (CR 58). Only the last three parts are structural, so the read is
    right-anchored. A key too short to carry one returns ``None`` — a probe
    degrades on a malformed row rather than crashing the nightly chain.
    """
    parts = source_id.rsplit(":", 3)
    return parts[1] if len(parts) == 4 else None


async def run_parity(
    session: AsyncSession,
    store: RawStore,
    roster_store: RawStore,
    sos_store: RawStore,
    *,
    baseline: int,
    current_biennium: str,
    role_baseline: int = ROLE_BASELINE_DIVERGENCE,
    sponsor_rows: Callable[[RawStore], list[dict[str, Any]]] = wsl.sponsor_rows,
    committee_member_rows: Callable[[RawStore], list[dict[str, Any]]] = wsl.committee_member_rows,
    roster_rows: Callable[[RawStore], list[dict[str, Any]]] = roster_staging.roster_rows,
    sos_result_rows: Callable[[RawStore], list[dict[str, Any]]] = sos_staging.result_rows,
) -> JobResult:
    """Diff the rebuilt spans against the canonical snapshot. Write-free.

    The staging readers are injected so the comparator and its exit gate are
    testable without a raw corpus (the shape :mod:`parity_wsl` uses).
    """
    if not store.latest():
        logger.warning("parity_spans_empty_store", extra={"source": SOURCE})
        return JobResult.degraded({"empty_store": True})
    if not roster_store.latest():
        # Without it the #228 deepening is lost and divergence explodes — which
        # would read as a regression in the port rather than a missing input.
        logger.warning("parity_spans_empty_roster_store", extra={"source": ROSTER_SOURCE})
        return JobResult.degraded({"empty_roster_store": True})

    # The guard belongs on the ROWS, not the store (CR 69): a store holding
    # wires that yield nothing must degrade with a named reason here, rather
    # than raising out of build_all_spans through the harness's exception
    # route — which loses the counters (#331).
    roster = roster_rows(roster_store)
    if not roster:
        logger.warning("parity_spans_empty_roster_rows", extra={"source": ROSTER_SOURCE})
        return JobResult.degraded({"empty_roster_rows": True})
    # PARTIAL malformation trips neither the CR-67 raise (records survive) nor
    # anything else — it quietly degrades the #228 deepening (CR 73). The build
    # re-parses; this parse is cheap and makes the number a gated counter
    # rather than a log line in a job whose logs nobody reads while it passes.
    malformed_roster_rows = len(roster) - len(roster_records(roster))

    sponsors = sponsor_rows(store)
    sos_results = sos_result_rows(sos_store)
    if sponsors and not sos_results:
        # The House family's ballot input, guarded like the roster tier's:
        # its absence deletes ~4% of the table, inside the publish shrink floor.
        logger.warning("parity_spans_empty_sos_rows", extra={"source": SOS_SOURCE})
        return JobResult.degraded({"empty_sos_rows": True})
    events = await operator_event_rows(session)
    # One resolve, both families — see `conformed.spans.roster_resolution`.
    resolution = roster_resolution(roster, sponsors)
    spans = build_all_spans(
        SpanInputs(
            sponsors=sponsors,
            committee_members=committee_member_rows(store),
            roster=roster,
            sos_results=sos_results,
            events=events,
        ),
        current_biennium=current_biennium,
        extra_observations=resolution.joined,
    )
    roster_spans = build_roster_spans(
        resolution, events=events, current_biennium=current_biennium, context_spans=spans
    )
    families = {SOURCE: spans, ROSTER_SOURCE: roster_spans}

    # Keyed by (source, source_id): the two families are disjoint identity
    # spaces sharing one table, and only the pair is unique by construction.
    ours = {
        (source, s.source_id): (s.valid_from, s.valid_to, s.is_active)
        for source, family in families.items()
        for s in family
    }
    canonical: dict[tuple[str, str], tuple[Any, Any, Any]] = {}
    unparsable = 0
    for row in (
        await session.execute(
            select(
                Assignment.source,
                Assignment.source_id,
                Assignment.valid_from,
                Assignment.valid_to,
                Assignment.is_active,
            ).where(Assignment.source.in_(tuple(families)))
        )
    ).all():
        kind = owned_kind(row[1])
        if kind is None:
            # Excluding a key that cannot carry a kind is right; excluding it
            # SILENTLY shrinks the oracle unnoticed (CR 70).
            unparsable += 1
        elif kind in OWNED_KINDS:
            canonical[(row[0], row[1])] = (row[2], row[3], row[4])
    if not canonical:
        # An empty oracle makes every comparison vacuously clean (#302 CR 6).
        logger.warning("parity_spans_empty_canonical", extra={"sources": sorted(families)})
        return JobResult.degraded({"empty_canonical": True, "spans": len(ours)})

    # The crosswalk join the `assignments` model performs, reported HERE
    # because the model cannot report it (CR 68): a `dbt build` never calls
    # `configure_logging`, so a logger inside a Python model emits nothing —
    # the info path is dropped outright and the warning path reaches
    # `logging.lastResort`, which prints the message and discards `extra`.
    # This probe runs under the job harness, so its counters are real JSON.
    #
    # NOT the same read the model made (CR 75): the nightly runs
    # `dbt build → registrar → publish → parity`, so the registrar may have
    # bound keys since. This measures the registry as it stands NOW — which is
    # the state tomorrow's build will publish from, so a gap here is the one
    # worth alarming on. A gap the registrar has since closed is transient and
    # self-healing, and correctly reads as zero.
    _rows, join = assignment_rows(
        families, entity_index(await crosswalk_rows(session, KIND_PERSON))
    )

    missing = sorted(set(canonical) - set(ours))
    extra = sorted(set(ours) - set(canonical))
    dated = sorted(k for k in set(ours) & set(canonical) if ours[k] != canonical[k])
    divergence = len(missing) + len(extra) + len(dated)
    # Finished before the role oracle is consulted, so a missing role dimension
    # cannot blind a span comparison that already succeeded (CR 85).
    counters: dict[str, Any] = {
        "spans": len(ours),
        "wsl_spans": len(spans),
        "roster_spans": len(roster_spans),
        "canonical": len(canonical),
        "missing": len(missing),
        "extra": len(extra),
        "dated_differently": len(dated),
        "divergence": divergence,
        "baseline": baseline,
        "registered_spans": join["published"],
        "unregistered_spans": join["unregistered_spans"],
        "malformed_roster_rows": malformed_roster_rows,
        "unparsable_canonical_keys": unparsable,
    }

    # The ROLE dimension, against the tier that already publishes these keys to
    # Power Map (CR 77). The dbt `assignments_name_a_role` test cannot catch a
    # fork: `roles` is generated by iterating `assignments` through the same
    # `role_for_span`, so containment holds by construction.
    #
    # Derived from the SPANS, not from `_rows` — this keeps the role parity a
    # statement about the DERIVATION rather than about the registry (CR 86).
    # From the crosswalk-joined rows a registrar gap would report as a phantom
    # role fork, sending the operator after the wrong defect, and it would hide
    # a genuine fork whose only spans happen to be unregistered.
    # `unregistered_orgs` is the roles model's own discarded counter (CR 78),
    # which a Python model cannot report for the reason above.
    derived_roles, role_join = role_rows(
        [
            {"span_kind": s.kind, "span_discriminator": s.discriminator}
            for family in families.values()
            for s in family
        ],
        entity_index(await crosswalk_rows(session, KIND_ORG)),
    )
    our_roles = {
        row["role_key"]: tuple(row[attr] for attr in ROLE_ATTRIBUTES) for row in derived_roles
    }
    canonical_roles = {
        row[0]: tuple(row[1:])
        for row in (
            await session.execute(
                select(
                    CanonicalRole.source_id,
                    *(getattr(CanonicalRole, attr) for attr in ROLE_ATTRIBUTES),
                ).where(
                    CanonicalRole.source == ROLE_SOURCE,
                    CanonicalRole.deleted_at.is_(None),
                )
            )
        ).all()
    }
    if not canonical_roles:
        # Same rule as the empty span oracle: report "no oracle", never a fork.
        logger.warning("parity_spans_empty_canonical_roles", extra={"source": ROLE_SOURCE})
        return JobResult.degraded(
            {**counters, "empty_canonical_roles": True, "roles": len(our_roles)}
        )
    role_only_ours = sorted(set(our_roles) - set(canonical_roles))
    role_only_canonical = sorted(set(canonical_roles) - set(our_roles))
    # Same KEY, different meaning — the #110 shape, where 305 party roles churned
    # on local `member` vs PM `party_member` with every key identical (CR 84).
    # One entry per differing attribute, so the sample names the field.
    attribute_mismatches = sorted(
        (key, attr, canonical_roles[key][i], our_roles[key][i])
        for key in set(our_roles) & set(canonical_roles)
        for i, attr in enumerate(ROLE_ATTRIBUTES)
        if our_roles[key][i] != canonical_roles[key][i]
    )
    counters.update(
        {
            "roles": len(our_roles),
            "canonical_roles": len(canonical_roles),
            "role_divergence": len(role_only_ours) + len(role_only_canonical),
            "role_baseline": role_baseline,
            "role_attribute_mismatches": len(attribute_mismatches),
            "unregistered_orgs": role_join["unregistered_orgs"],
        }
    )

    counters["integrity_failures"] = [c for c in INTEGRITY_COUNTERS if counters[c]]
    # Two ratchets share one exit code, so each says whether it was the one that
    # moved — the `integrity_failures` principle (CR 72/73), applied to the
    # counters that are compared against a baseline rather than against 0.
    counters["ratchet_failures"] = [
        name
        for name, value, limit in (
            ("divergence", divergence, baseline),
            ("role_divergence", counters["role_divergence"], role_baseline),
        )
        if value > limit
    ]
    clean = not counters["ratchet_failures"] and not counters["integrity_failures"]
    log = logger.info if clean else logger.error
    log(
        "parity_spans_report",
        extra={
            "summary": counters,
            "missing_sample": [f"{src}/{sid}" for src, sid in missing[:20]],
            "extra_sample": [f"{src}/{sid}" for src, sid in extra[:20]],
            "dated_sample": [f"{src}/{sid}" for src, sid in dated[:20]],
            "role_only_ours_sample": role_only_ours[:20],
            "role_only_canonical_sample": role_only_canonical[:20],
            "role_attribute_sample": [
                f"{key}.{attr}: canonical={theirs!r} ours={mine!r}"
                for key, attr, theirs, mine in attribute_mismatches[:20]
            ],
        },
    )
    if not clean:
        return JobResult.failed(counters, exit_code=1)
    return JobResult.ok(counters)


async def _parity_job(ctx: JobContext) -> JobResult:
    """Bind the probe to the real raw root and the current biennium."""
    root = Path(ctx.args.root) if ctx.args.root else get_raw_root()
    return await run_parity(
        ctx.require_session(),
        RawStore(root, SOURCE),
        RawStore(root, ROSTER_SOURCE),
        RawStore(root, SOS_SOURCE),
        baseline=ctx.args.baseline,
        role_baseline=ctx.args.role_baseline,
        current_biennium=(
            os.environ.get("USA_WA_BIENNIUM") or biennium_for_date(datetime.now(UTC).date())
        ),
    )


def main(argv: list[str] | None = None) -> int:
    """Diff conformed spans against the canonical assignment snapshot."""
    return run_job(
        JOB_SLUG,
        _parity_job,
        argv=argv,
        prog="python -m usa_wa_pipeline.parity_spans",
        description="Write-free parity: conformed tenure spans vs canonical assignments (#309).",
        extra_args=_add_args,
        commit=False,
        dry_run=False,
    )


if __name__ == "__main__":
    raise SystemExit(main())
