"""add retired_at tombstone to identity models (#31)

Revision ID: 136d33aa41b8
Revises: a1c7e9d2f3b4
Create Date: 2026-06-23 13:09:55.566444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136d33aa41b8'
down_revision: Union[str, Sequence[str], None] = 'a1c7e9d2f3b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True), schema='canonical')
    op.add_column('organizations', sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True), schema='canonical')
    op.add_column('persons', sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True), schema='canonical')
    op.add_column('roles', sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True), schema='canonical')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'retired_at', schema='canonical')
    op.drop_column('persons', 'retired_at', schema='canonical')
    op.drop_column('organizations', 'retired_at', schema='canonical')
    op.drop_column('assignments', 'retired_at', schema='canonical')
    # ### end Alembic commands ###
