"""canonical init — materializes the hybrid IA v1 (Person/Org/Role/Assignment + bills/votes/statutes/pdc).

Revision ID: 20260527_canonical_init
Revises: 20260526_chcore_init
Create Date: 2026-05-27
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import clearinghouse_core.db.ulid

revision: str = "20260527_canonical_init"
down_revision: str | Sequence[str] | None = "20260526_chcore_init"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SCHEMA = "canonical"


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(f'CREATE SCHEMA IF NOT EXISTS "{SCHEMA}"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legislative_sessions',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('biennium_label', sa.String(length=16), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction_id', 'slug', name='uq_legislative_sessions_slug'),
    sa.UniqueConstraint('jurisdiction_id', 'source', 'source_id', name='uq_legislative_sessions_natural_key'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_legislative_sessions_jurisdiction_id'), 'legislative_sessions', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_table('organizations',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('short_name', sa.String(length=128), nullable=True),
    sa.Column('org_type', sa.String(length=32), nullable=False),
    sa.Column('parent_organization_id', clearinghouse_core.db.ulid.ULID(), nullable=True),
    sa.Column('powermap_organization_id', clearinghouse_core.db.ulid.ULID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_organization_id'], ['canonical.organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction_id', 'source', 'source_id', name='uq_organizations_natural_key'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_organizations_jurisdiction_id'), 'organizations', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_organizations_parent_organization_id'), 'organizations', ['parent_organization_id'], unique=False, schema='canonical')
    op.create_table('persons',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('name_full', sa.String(length=256), nullable=False),
    sa.Column('name_first', sa.String(length=128), nullable=True),
    sa.Column('name_last', sa.String(length=128), nullable=True),
    sa.Column('name_middle', sa.String(length=128), nullable=True),
    sa.Column('name_suffix', sa.String(length=32), nullable=True),
    sa.Column('name_used', sa.String(length=256), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('powermap_person_id', clearinghouse_core.db.ulid.ULID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction_id', 'source', 'source_id', name='uq_persons_natural_key'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_persons_jurisdiction_id'), 'persons', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_table('statute_codes',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction_id', 'code', name='uq_statute_codes_natural_key'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_statute_codes_jurisdiction_id'), 'statute_codes', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_table('bills',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('legislative_session_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('originating_chamber', sa.String(length=16), nullable=False),
    sa.Column('current_chamber', sa.String(length=16), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('bill_type', sa.String(length=32), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('current_status', sa.String(length=128), nullable=True),
    sa.Column('current_status_class', sa.String(length=32), nullable=True),
    sa.Column('current_status_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('introduced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enacted_as', sa.String(length=64), nullable=True),
    sa.Column('current_text', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['legislative_session_id'], ['canonical.legislative_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction_id', 'source', 'source_id', name='uq_bills_natural_key'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_bills_jurisdiction_id'), 'bills', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_bills_legislative_session_id'), 'bills', ['legislative_session_id'], unique=False, schema='canonical')
    op.create_table('contributions',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('recipient_organization_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('contributor_person_id', clearinghouse_core.db.ulid.ULID(), nullable=True),
    sa.Column('contributor_organization_id', clearinghouse_core.db.ulid.ULID(), nullable=True),
    sa.Column('contributor_name_raw', sa.String(length=512), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('contributed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT (contributor_person_id IS NOT NULL AND contributor_organization_id IS NOT NULL)', name='ck_contributions_at_most_one_contributor'),
    sa.ForeignKeyConstraint(['contributor_organization_id'], ['canonical.organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contributor_person_id'], ['canonical.persons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_organization_id'], ['canonical.organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction_id', 'source', 'source_id', name='uq_contributions_natural_key'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_contributions_contributor_organization_id'), 'contributions', ['contributor_organization_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_contributions_contributor_person_id'), 'contributions', ['contributor_person_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_contributions_jurisdiction_id'), 'contributions', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_contributions_recipient_organization_id'), 'contributions', ['recipient_organization_id'], unique=False, schema='canonical')
    op.create_table('lobbying_activities',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('person_id', clearinghouse_core.db.ulid.ULID(), nullable=True),
    sa.Column('organization_id', clearinghouse_core.db.ulid.ULID(), nullable=True),
    sa.Column('employer_organization_id', clearinghouse_core.db.ulid.ULID(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('compensation', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expenses', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('person_id IS NOT NULL OR organization_id IS NOT NULL', name='ck_lobbying_activities_person_or_org'),
    sa.ForeignKeyConstraint(['employer_organization_id'], ['canonical.organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['canonical.organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_id'], ['canonical.persons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction_id', 'source', 'source_id', name='uq_lobbying_activities_natural_key'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_lobbying_activities_jurisdiction_id'), 'lobbying_activities', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_lobbying_activities_organization_id'), 'lobbying_activities', ['organization_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_lobbying_activities_person_id'), 'lobbying_activities', ['person_id'], unique=False, schema='canonical')
    op.create_table('organization_identifiers',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('organization_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('scheme', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('verified_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['canonical.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction_id', 'scheme', 'value', name='uq_organization_identifiers_jurisdiction_scheme_value'),
    sa.UniqueConstraint('jurisdiction_id', 'source', 'source_id', name='uq_organization_identifiers_natural_key'),
    sa.UniqueConstraint('organization_id', 'scheme', name='uq_organization_identifiers_org_scheme'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_organization_identifiers_jurisdiction_id'), 'organization_identifiers', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_organization_identifiers_organization_id'), 'organization_identifiers', ['organization_id'], unique=False, schema='canonical')
    op.create_table('person_identifiers',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('person_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('scheme', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('verified_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['canonical.persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction_id', 'scheme', 'value', name='uq_person_identifiers_jurisdiction_scheme_value'),
    sa.UniqueConstraint('jurisdiction_id', 'source', 'source_id', name='uq_person_identifiers_natural_key'),
    sa.UniqueConstraint('person_id', 'scheme', name='uq_person_identifiers_person_scheme'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_person_identifiers_jurisdiction_id'), 'person_identifiers', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_person_identifiers_person_id'), 'person_identifiers', ['person_id'], unique=False, schema='canonical')
    op.create_table('roles',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('organization_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('role_type', sa.String(length=32), nullable=False),
    sa.Column('district', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['canonical.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction_id', 'organization_id', 'name', 'district', name='uq_roles_org_name_district'),
    sa.UniqueConstraint('jurisdiction_id', 'source', 'source_id', name='uq_roles_natural_key'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_roles_jurisdiction_id'), 'roles', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_roles_organization_id'), 'roles', ['organization_id'], unique=False, schema='canonical')
    op.create_table('statute_titles',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('statute_code_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('heading', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['statute_code_id'], ['canonical.statute_codes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('statute_code_id', 'number', name='uq_statute_titles_natural_key'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_statute_titles_jurisdiction_id'), 'statute_titles', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_statute_titles_statute_code_id'), 'statute_titles', ['statute_code_id'], unique=False, schema='canonical')
    op.create_table('amendments',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('bill_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('amendment_text', sa.Text(), nullable=True),
    sa.Column('sponsor_person_id', clearinghouse_core.db.ulid.ULID(), nullable=True),
    sa.Column('sponsor_organization_id', clearinghouse_core.db.ulid.ULID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('offered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('adopted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['canonical.bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sponsor_organization_id'], ['canonical.organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sponsor_person_id'], ['canonical.persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction_id', 'source', 'source_id', name='uq_amendments_natural_key'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_amendments_bill_id'), 'amendments', ['bill_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_amendments_jurisdiction_id'), 'amendments', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_table('assignments',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('person_id', clearinghouse_core.db.ulid.ULID(), nullable=True),
    sa.Column('holder_name_raw', sa.String(length=256), nullable=True),
    sa.Column('role_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('person_id IS NOT NULL OR holder_name_raw IS NOT NULL', name='ck_assignments_person_or_name'),
    sa.ForeignKeyConstraint(['person_id'], ['canonical.persons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['canonical.roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction_id', 'source', 'source_id', name='uq_assignments_natural_key'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_assignments_jurisdiction_id'), 'assignments', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_assignments_person_id'), 'assignments', ['person_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_assignments_role_id'), 'assignments', ['role_id'], unique=False, schema='canonical')
    op.create_table('bill_actions',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('bill_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('action_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('chamber', sa.String(length=16), nullable=True),
    sa.Column('acting_organization_id', clearinghouse_core.db.ulid.ULID(), nullable=True),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('primary_classification', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_major', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acting_organization_id'], ['canonical.organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bill_id'], ['canonical.bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction_id', 'source', 'source_id', name='uq_bill_actions_natural_key'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_bill_actions_acting_organization_id'), 'bill_actions', ['acting_organization_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_bill_actions_bill_id'), 'bill_actions', ['bill_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_bill_actions_jurisdiction_id'), 'bill_actions', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_table('bill_events',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('bill_id', clearinghouse_core.db.ulid.ULID(), nullable=True),
    sa.Column('organization_id', clearinghouse_core.db.ulid.ULID(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['canonical.bills.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['canonical.organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction_id', 'source', 'source_id', name='uq_bill_events_natural_key'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_bill_events_bill_id'), 'bill_events', ['bill_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_bill_events_jurisdiction_id'), 'bill_events', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_bill_events_organization_id'), 'bill_events', ['organization_id'], unique=False, schema='canonical')
    op.create_table('bill_relationships',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('from_bill_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('to_bill_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_bill_id'], ['canonical.bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_bill_id'], ['canonical.bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_bill_id', 'to_bill_id', 'relationship_type', name='uq_bill_relationships_pair_type'),
    sa.UniqueConstraint('jurisdiction_id', 'source', 'source_id', name='uq_bill_relationships_natural_key'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_bill_relationships_from_bill_id'), 'bill_relationships', ['from_bill_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_bill_relationships_jurisdiction_id'), 'bill_relationships', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_bill_relationships_to_bill_id'), 'bill_relationships', ['to_bill_id'], unique=False, schema='canonical')
    op.create_table('bill_sponsorships',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('bill_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('person_id', clearinghouse_core.db.ulid.ULID(), nullable=True),
    sa.Column('organization_id', clearinghouse_core.db.ulid.ULID(), nullable=True),
    sa.Column('sponsor_name_raw', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('sponsor_order', sa.Integer(), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(person_id IS NOT NULL AND organization_id IS NULL) OR (person_id IS NULL AND organization_id IS NOT NULL) OR (person_id IS NULL AND organization_id IS NULL AND sponsor_name_raw IS NOT NULL)', name='ck_bill_sponsorships_polymorphic'),
    sa.ForeignKeyConstraint(['bill_id'], ['canonical.bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['canonical.organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_id'], ['canonical.persons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction_id', 'source', 'source_id', name='uq_bill_sponsorships_natural_key'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_bill_sponsorships_bill_id'), 'bill_sponsorships', ['bill_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_bill_sponsorships_jurisdiction_id'), 'bill_sponsorships', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_table('bill_subjects',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('bill_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['canonical.bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_id', 'subject', name='uq_bill_subjects_bill_subject'),
    sa.UniqueConstraint('jurisdiction_id', 'source', 'source_id', name='uq_bill_subjects_natural_key'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_bill_subjects_bill_id'), 'bill_subjects', ['bill_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_bill_subjects_jurisdiction_id'), 'bill_subjects', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_table('bill_versions',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('bill_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('version_type', sa.String(length=64), nullable=False),
    sa.Column('version_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['canonical.bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction_id', 'source', 'source_id', name='uq_bill_versions_natural_key'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_bill_versions_bill_id'), 'bill_versions', ['bill_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_bill_versions_jurisdiction_id'), 'bill_versions', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_table('lobbying_positions',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('lobbying_activity_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('bill_id', clearinghouse_core.db.ulid.ULID(), nullable=True),
    sa.Column('bill_reference_raw', sa.String(length=128), nullable=True),
    sa.Column('position', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['canonical.bills.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lobbying_activity_id'], ['canonical.lobbying_activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction_id', 'source', 'source_id', name='uq_lobbying_positions_natural_key'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_lobbying_positions_bill_id'), 'lobbying_positions', ['bill_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_lobbying_positions_jurisdiction_id'), 'lobbying_positions', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_lobbying_positions_lobbying_activity_id'), 'lobbying_positions', ['lobbying_activity_id'], unique=False, schema='canonical')
    op.create_table('statute_chapters',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('statute_title_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('heading', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['statute_title_id'], ['canonical.statute_titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('statute_title_id', 'number', name='uq_statute_chapters_natural_key'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_statute_chapters_jurisdiction_id'), 'statute_chapters', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_statute_chapters_statute_title_id'), 'statute_chapters', ['statute_title_id'], unique=False, schema='canonical')
    op.create_table('bill_action_classifications',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('bill_action_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('classification', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_action_id'], ['canonical.bill_actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_action_id', 'classification', name='uq_bill_action_classifications_action_class'),
    sa.UniqueConstraint('jurisdiction_id', 'source', 'source_id', name='uq_bill_action_classifications_natural_key'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_bill_action_classifications_bill_action_id'), 'bill_action_classifications', ['bill_action_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_bill_action_classifications_jurisdiction_id'), 'bill_action_classifications', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_table('statute_sections',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('statute_chapter_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('heading', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['statute_chapter_id'], ['canonical.statute_chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('statute_chapter_id', 'number', name='uq_statute_sections_natural_key'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_statute_sections_jurisdiction_id'), 'statute_sections', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_statute_sections_statute_chapter_id'), 'statute_sections', ['statute_chapter_id'], unique=False, schema='canonical')
    op.create_table('vote_events',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('subject_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('bill_id', clearinghouse_core.db.ulid.ULID(), nullable=True),
    sa.Column('amendment_id', clearinghouse_core.db.ulid.ULID(), nullable=True),
    sa.Column('motion_description', sa.Text(), nullable=True),
    sa.Column('context_type', sa.String(length=16), nullable=False),
    sa.Column('context_organization_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('chamber', sa.String(length=16), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['amendment_id'], ['canonical.amendments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bill_id'], ['canonical.bills.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['context_organization_id'], ['canonical.organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction_id', 'source', 'source_id', name='uq_vote_events_natural_key'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_vote_events_amendment_id'), 'vote_events', ['amendment_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_vote_events_bill_id'), 'vote_events', ['bill_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_vote_events_context_organization_id'), 'vote_events', ['context_organization_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_vote_events_jurisdiction_id'), 'vote_events', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_table('bill_statute_changes',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('bill_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('statute_section_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('change_type', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['canonical.bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['statute_section_id'], ['canonical.statute_sections.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_id', 'statute_section_id', 'change_type', name='uq_bill_statute_changes_natural_key'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_bill_statute_changes_bill_id'), 'bill_statute_changes', ['bill_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_bill_statute_changes_jurisdiction_id'), 'bill_statute_changes', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_bill_statute_changes_statute_section_id'), 'bill_statute_changes', ['statute_section_id'], unique=False, schema='canonical')
    op.create_table('person_votes',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('vote_event_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('person_id', clearinghouse_core.db.ulid.ULID(), nullable=True),
    sa.Column('voter_name_raw', sa.String(length=256), nullable=True),
    sa.Column('vote', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('person_id IS NOT NULL OR voter_name_raw IS NOT NULL', name='ck_person_votes_person_or_name'),
    sa.ForeignKeyConstraint(['person_id'], ['canonical.persons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vote_event_id'], ['canonical.vote_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction_id', 'source', 'source_id', name='uq_person_votes_natural_key'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_person_votes_jurisdiction_id'), 'person_votes', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_person_votes_person_id'), 'person_votes', ['person_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_person_votes_vote_event_id'), 'person_votes', ['vote_event_id'], unique=False, schema='canonical')
    op.create_table('vote_counts',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('vote_event_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('count_type', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vote_event_id'], ['canonical.vote_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction_id', 'source', 'source_id', name='uq_vote_counts_natural_key'),
    sa.UniqueConstraint('vote_event_id', 'count_type', name='uq_vote_counts_event_type'),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_vote_counts_jurisdiction_id'), 'vote_counts', ['jurisdiction_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_vote_counts_vote_event_id'), 'vote_counts', ['vote_event_id'], unique=False, schema='canonical')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_canonical_vote_counts_vote_event_id'), table_name='vote_counts', schema='canonical')
    op.drop_index(op.f('ix_canonical_vote_counts_jurisdiction_id'), table_name='vote_counts', schema='canonical')
    op.drop_table('vote_counts', schema='canonical')
    op.drop_index(op.f('ix_canonical_person_votes_vote_event_id'), table_name='person_votes', schema='canonical')
    op.drop_index(op.f('ix_canonical_person_votes_person_id'), table_name='person_votes', schema='canonical')
    op.drop_index(op.f('ix_canonical_person_votes_jurisdiction_id'), table_name='person_votes', schema='canonical')
    op.drop_table('person_votes', schema='canonical')
    op.drop_index(op.f('ix_canonical_bill_statute_changes_statute_section_id'), table_name='bill_statute_changes', schema='canonical')
    op.drop_index(op.f('ix_canonical_bill_statute_changes_jurisdiction_id'), table_name='bill_statute_changes', schema='canonical')
    op.drop_index(op.f('ix_canonical_bill_statute_changes_bill_id'), table_name='bill_statute_changes', schema='canonical')
    op.drop_table('bill_statute_changes', schema='canonical')
    op.drop_index(op.f('ix_canonical_vote_events_jurisdiction_id'), table_name='vote_events', schema='canonical')
    op.drop_index(op.f('ix_canonical_vote_events_context_organization_id'), table_name='vote_events', schema='canonical')
    op.drop_index(op.f('ix_canonical_vote_events_bill_id'), table_name='vote_events', schema='canonical')
    op.drop_index(op.f('ix_canonical_vote_events_amendment_id'), table_name='vote_events', schema='canonical')
    op.drop_table('vote_events', schema='canonical')
    op.drop_index(op.f('ix_canonical_statute_sections_statute_chapter_id'), table_name='statute_sections', schema='canonical')
    op.drop_index(op.f('ix_canonical_statute_sections_jurisdiction_id'), table_name='statute_sections', schema='canonical')
    op.drop_table('statute_sections', schema='canonical')
    op.drop_index(op.f('ix_canonical_bill_action_classifications_jurisdiction_id'), table_name='bill_action_classifications', schema='canonical')
    op.drop_index(op.f('ix_canonical_bill_action_classifications_bill_action_id'), table_name='bill_action_classifications', schema='canonical')
    op.drop_table('bill_action_classifications', schema='canonical')
    op.drop_index(op.f('ix_canonical_statute_chapters_statute_title_id'), table_name='statute_chapters', schema='canonical')
    op.drop_index(op.f('ix_canonical_statute_chapters_jurisdiction_id'), table_name='statute_chapters', schema='canonical')
    op.drop_table('statute_chapters', schema='canonical')
    op.drop_index(op.f('ix_canonical_lobbying_positions_lobbying_activity_id'), table_name='lobbying_positions', schema='canonical')
    op.drop_index(op.f('ix_canonical_lobbying_positions_jurisdiction_id'), table_name='lobbying_positions', schema='canonical')
    op.drop_index(op.f('ix_canonical_lobbying_positions_bill_id'), table_name='lobbying_positions', schema='canonical')
    op.drop_table('lobbying_positions', schema='canonical')
    op.drop_index(op.f('ix_canonical_bill_versions_jurisdiction_id'), table_name='bill_versions', schema='canonical')
    op.drop_index(op.f('ix_canonical_bill_versions_bill_id'), table_name='bill_versions', schema='canonical')
    op.drop_table('bill_versions', schema='canonical')
    op.drop_index(op.f('ix_canonical_bill_subjects_jurisdiction_id'), table_name='bill_subjects', schema='canonical')
    op.drop_index(op.f('ix_canonical_bill_subjects_bill_id'), table_name='bill_subjects', schema='canonical')
    op.drop_table('bill_subjects', schema='canonical')
    op.drop_index(op.f('ix_canonical_bill_sponsorships_jurisdiction_id'), table_name='bill_sponsorships', schema='canonical')
    op.drop_index(op.f('ix_canonical_bill_sponsorships_bill_id'), table_name='bill_sponsorships', schema='canonical')
    op.drop_table('bill_sponsorships', schema='canonical')
    op.drop_index(op.f('ix_canonical_bill_relationships_to_bill_id'), table_name='bill_relationships', schema='canonical')
    op.drop_index(op.f('ix_canonical_bill_relationships_jurisdiction_id'), table_name='bill_relationships', schema='canonical')
    op.drop_index(op.f('ix_canonical_bill_relationships_from_bill_id'), table_name='bill_relationships', schema='canonical')
    op.drop_table('bill_relationships', schema='canonical')
    op.drop_index(op.f('ix_canonical_bill_events_organization_id'), table_name='bill_events', schema='canonical')
    op.drop_index(op.f('ix_canonical_bill_events_jurisdiction_id'), table_name='bill_events', schema='canonical')
    op.drop_index(op.f('ix_canonical_bill_events_bill_id'), table_name='bill_events', schema='canonical')
    op.drop_table('bill_events', schema='canonical')
    op.drop_index(op.f('ix_canonical_bill_actions_jurisdiction_id'), table_name='bill_actions', schema='canonical')
    op.drop_index(op.f('ix_canonical_bill_actions_bill_id'), table_name='bill_actions', schema='canonical')
    op.drop_index(op.f('ix_canonical_bill_actions_acting_organization_id'), table_name='bill_actions', schema='canonical')
    op.drop_table('bill_actions', schema='canonical')
    op.drop_index(op.f('ix_canonical_assignments_role_id'), table_name='assignments', schema='canonical')
    op.drop_index(op.f('ix_canonical_assignments_person_id'), table_name='assignments', schema='canonical')
    op.drop_index(op.f('ix_canonical_assignments_jurisdiction_id'), table_name='assignments', schema='canonical')
    op.drop_table('assignments', schema='canonical')
    op.drop_index(op.f('ix_canonical_amendments_jurisdiction_id'), table_name='amendments', schema='canonical')
    op.drop_index(op.f('ix_canonical_amendments_bill_id'), table_name='amendments', schema='canonical')
    op.drop_table('amendments', schema='canonical')
    op.drop_index(op.f('ix_canonical_statute_titles_statute_code_id'), table_name='statute_titles', schema='canonical')
    op.drop_index(op.f('ix_canonical_statute_titles_jurisdiction_id'), table_name='statute_titles', schema='canonical')
    op.drop_table('statute_titles', schema='canonical')
    op.drop_index(op.f('ix_canonical_roles_organization_id'), table_name='roles', schema='canonical')
    op.drop_index(op.f('ix_canonical_roles_jurisdiction_id'), table_name='roles', schema='canonical')
    op.drop_table('roles', schema='canonical')
    op.drop_index(op.f('ix_canonical_person_identifiers_person_id'), table_name='person_identifiers', schema='canonical')
    op.drop_index(op.f('ix_canonical_person_identifiers_jurisdiction_id'), table_name='person_identifiers', schema='canonical')
    op.drop_table('person_identifiers', schema='canonical')
    op.drop_index(op.f('ix_canonical_organization_identifiers_organization_id'), table_name='organization_identifiers', schema='canonical')
    op.drop_index(op.f('ix_canonical_organization_identifiers_jurisdiction_id'), table_name='organization_identifiers', schema='canonical')
    op.drop_table('organization_identifiers', schema='canonical')
    op.drop_index(op.f('ix_canonical_lobbying_activities_person_id'), table_name='lobbying_activities', schema='canonical')
    op.drop_index(op.f('ix_canonical_lobbying_activities_organization_id'), table_name='lobbying_activities', schema='canonical')
    op.drop_index(op.f('ix_canonical_lobbying_activities_jurisdiction_id'), table_name='lobbying_activities', schema='canonical')
    op.drop_table('lobbying_activities', schema='canonical')
    op.drop_index(op.f('ix_canonical_contributions_recipient_organization_id'), table_name='contributions', schema='canonical')
    op.drop_index(op.f('ix_canonical_contributions_jurisdiction_id'), table_name='contributions', schema='canonical')
    op.drop_index(op.f('ix_canonical_contributions_contributor_person_id'), table_name='contributions', schema='canonical')
    op.drop_index(op.f('ix_canonical_contributions_contributor_organization_id'), table_name='contributions', schema='canonical')
    op.drop_table('contributions', schema='canonical')
    op.drop_index(op.f('ix_canonical_bills_legislative_session_id'), table_name='bills', schema='canonical')
    op.drop_index(op.f('ix_canonical_bills_jurisdiction_id'), table_name='bills', schema='canonical')
    op.drop_table('bills', schema='canonical')
    op.drop_index(op.f('ix_canonical_statute_codes_jurisdiction_id'), table_name='statute_codes', schema='canonical')
    op.drop_table('statute_codes', schema='canonical')
    op.drop_index(op.f('ix_canonical_persons_jurisdiction_id'), table_name='persons', schema='canonical')
    op.drop_table('persons', schema='canonical')
    op.drop_index(op.f('ix_canonical_organizations_parent_organization_id'), table_name='organizations', schema='canonical')
    op.drop_index(op.f('ix_canonical_organizations_jurisdiction_id'), table_name='organizations', schema='canonical')
    op.drop_table('organizations', schema='canonical')
    op.drop_index(op.f('ix_canonical_legislative_sessions_jurisdiction_id'), table_name='legislative_sessions', schema='canonical')
    op.drop_table('legislative_sessions', schema='canonical')
    # ### end Alembic commands ###

    op.execute(f'DROP SCHEMA IF EXISTS "{SCHEMA}" CASCADE')
