"""committee succession events (124)

Revision ID: 2365a8eceb9e
Revises: 73256e626f42
Create Date: 2026-07-25 22:40:14.920275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import clearinghouse_core.db.ulid


# revision identifiers, used by Alembic.
revision: str = '2365a8eceb9e'
down_revision: Union[str, Sequence[str], None] = '73256e626f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committee_succession_events',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=256), nullable=False),
    sa.Column('subject_source_id', sa.String(length=128), nullable=False),
    sa.Column('linked_source_id', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('effective_year', sa.Integer(), nullable=True),
    sa.Column('evidence_url', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('entered_by', sa.String(length=128), nullable=True),
    sa.Column('superseded_by_id', clearinghouse_core.db.ulid.ULID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("slug IN ('succeeded_by', 'split_from', 'merged_with')", name='ck_committee_succession_slug'),
    sa.CheckConstraint('subject_source_id <> linked_source_id', name='ck_committee_succession_distinct_ends'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['canonical.committee_succession_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_committee_succession_natural_key'),
    schema='canonical'
    )
    op.create_index('ix_committee_succession_linked', 'committee_succession_events', ['linked_source_id'], unique=False, schema='canonical')
    op.create_index('ix_committee_succession_subject', 'committee_succession_events', ['subject_source_id'], unique=False, schema='canonical')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_committee_succession_subject', table_name='committee_succession_events', schema='canonical')
    op.drop_index('ix_committee_succession_linked', table_name='committee_succession_events', schema='canonical')
    op.drop_table('committee_succession_events', schema='canonical')
    # ### end Alembic commands ###
