"""314 step C: drop the PM read-mirrors and the sync schema

The ungated half of the #302 cutover's deletion sweep. Ten tables and one
schema, with no dependants: no inbound foreign keys, no triggers and no
functions reference any of them, verified before this was written.

**The four canonical mirrors** — ``organization_names`` (323 rows),
``organization_acronyms`` (240), ``entity_events`` (467), ``role_types`` (13) —
mirrored Power Map state into the schema the serving projection reads from.
Each had exactly one writer, the sidecar's read-mirror, and no reader outside
it, which is why #314 marked them ``retired`` rather than ``declared``. Step B
deleted the writer, leaving four tables holding a frozen copy of PM's state as
of 2026-09-08 that nothing maintains. Their ``pm_*`` anchors go with them.

**The six sync tables** — the sidecar's outbox (84,152 rows), conditional-GET
state, enrich fingerprints, non-convergence state, the anchor re-anchor log and
sync state — plus the schema itself. usa-wa pushes nothing to PM as of #314; PM
pulls published datasets instead.

**NOT the four live anchor columns.** ``persons.pm_person_id``,
``organizations.pm_organization_id``, ``roles.pm_role_id`` and
``assignments.pm_assignment_id`` stay until power-map#500 lands, because PM
archives against them. That dependency is the whole reason step C splits in two,
and nothing here touches a table that still has a producer.

The data loss is intended, and every row was a copy of PM's own state — PM still
holds the originals.

Revision ID: 5079afab4030
Revises: 3c9d1e7f42ab
Create Date: 2026-09-18 18:06:29.240834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5079afab4030'
down_revision: Union[str, Sequence[str], None] = '3c9d1e7f42ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Drop the ten tables, then the schema that held six of them."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_canonical_role_types_pm_role_type_id'), table_name='role_types', schema='canonical')
    op.drop_table('role_types', schema='canonical')
    op.drop_index(op.f('ix_canonical_organization_names_organization_id'), table_name='organization_names', schema='canonical')
    op.drop_index(op.f('ix_canonical_organization_names_pm_org_name_id'), table_name='organization_names', schema='canonical')
    op.drop_table('organization_names', schema='canonical')
    op.drop_table('powermap_conditional_get_state', schema='sync')
    op.drop_index(op.f('ix_powermap_outbox_due'), table_name='powermap_outbox', schema='sync')
    op.drop_index(op.f('uq_powermap_outbox_open'), table_name='powermap_outbox', schema='sync', postgresql_where="((status)::text = 'PENDING'::text)")
    op.drop_table('powermap_outbox', schema='sync')
    op.drop_index(op.f('ix_canonical_entity_events_entity_id'), table_name='entity_events', schema='canonical')
    op.drop_index(op.f('ix_canonical_entity_events_pm_entity_event_id'), table_name='entity_events', schema='canonical')
    op.drop_table('entity_events', schema='canonical')
    op.drop_index(op.f('ix_powermap_anchor_reanchor_old'), table_name='powermap_anchor_reanchor', schema='sync')
    op.drop_table('powermap_anchor_reanchor', schema='sync')
    op.drop_index(op.f('ix_canonical_organization_acronyms_organization_id'), table_name='organization_acronyms', schema='canonical')
    op.drop_index(op.f('ix_canonical_organization_acronyms_pm_org_acronym_id'), table_name='organization_acronyms', schema='canonical')
    op.drop_table('organization_acronyms', schema='canonical')
    op.drop_index(op.f('ix_powermap_nonconvergence_state_count'), table_name='powermap_nonconvergence_state', schema='sync')
    op.drop_table('powermap_nonconvergence_state', schema='sync')
    op.drop_table('powermap_sync_state', schema='sync')
    op.drop_table('powermap_enrich_fingerprint', schema='sync')
    # The schema itself, not only its tables. An empty `sync` left standing
    # reads to an operator as a thing that might still fill up, and would keep
    # `testing.LEGACY_MIGRATION_SCHEMAS`' entry load-bearing at head rather than
    # only mid-chain. CASCADE covers the sequences and types those tables owned;
    # every table is already dropped above, so it takes nothing this file has
    # not named. IF EXISTS so a replay that never reached the creating revision
    # is not an error.
    op.execute("DROP SCHEMA IF EXISTS sync CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Recreate the structures. The rows do not come back.

    A real downgrade rather than a raise, so the chain stays reversible either
    side of this revision — but what returns is ten empty tables that nothing
    writes, because this revision removes the last trace of their only writer.
    Restoring the DATA means re-reading it from Power Map, which holds every
    original.
    """
    op.execute("CREATE SCHEMA IF NOT EXISTS sync")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('powermap_enrich_fingerprint',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('local_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('payload_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('powermap_enrich_fingerprint_pkey')),
    sa.UniqueConstraint('entity_type', 'local_id', name=op.f('uq_powermap_enrich_fingerprint_row'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='sync'
    )
    op.create_table('powermap_sync_state',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stream', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('cursor', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('last_reconcile_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('powermap_sync_state_pkey')),
    sa.UniqueConstraint('stream', name=op.f('uq_powermap_sync_state_stream'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='sync'
    )
    op.create_table('powermap_nonconvergence_state',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('local_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('payload_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('powermap_nonconvergence_state_pkey')),
    sa.UniqueConstraint('entity_type', 'local_id', name=op.f('uq_powermap_nonconvergence_state_row'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='sync'
    )
    op.create_index(op.f('ix_powermap_nonconvergence_state_count'), 'powermap_nonconvergence_state', ['count'], unique=False, schema='sync')
    op.create_table('organization_acronyms',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('acronym', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('is_canonical', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('pm_org_acronym_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['canonical.organizations.id'], name=op.f('organization_acronyms_organization_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('organization_acronyms_pkey')),
    sa.UniqueConstraint('source', 'source_id', name=op.f('uq_organization_acronyms_natural_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_organization_acronyms_pm_org_acronym_id'), 'organization_acronyms', ['pm_org_acronym_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_organization_acronyms_organization_id'), 'organization_acronyms', ['organization_id'], unique=False, schema='canonical')
    op.create_table('powermap_anchor_reanchor',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('local_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('old_pm_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('new_pm_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('disposition', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('powermap_anchor_reanchor_pkey')),
    schema='sync'
    )
    op.create_index(op.f('ix_powermap_anchor_reanchor_old'), 'powermap_anchor_reanchor', ['old_pm_id'], unique=False, schema='sync')
    op.create_table('entity_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('entity_kind', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pm_entity_event_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('event_type_slug', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('event_type_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_hour', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_minute', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_second', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_place_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('visibility', sa.VARCHAR(length=16), server_default=sa.text("'public'::character varying"), autoincrement=False, nullable=False),
    sa.Column('linked_entity_kind', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('linked_entity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_place_address', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('verified_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pm_created_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retracted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("entity_kind::text = ANY (ARRAY['person'::character varying, 'organization'::character varying]::text[])", name=op.f('ck_entity_events_kind')),
    sa.CheckConstraint("linked_entity_kind IS NULL OR (linked_entity_kind::text = ANY (ARRAY['person'::character varying, 'organization'::character varying]::text[]))", name=op.f('ck_entity_events_linked_entity_kind')),
    sa.CheckConstraint("visibility::text = ANY (ARRAY['public'::character varying, 'legal_only'::character varying, 'hidden'::character varying]::text[])", name=op.f('ck_entity_events_visibility')),
    sa.CheckConstraint('event_type_slug IS NOT NULL) <> (event_type_id IS NOT NULL', name=op.f('ck_entity_events_event_type_xor')),
    sa.CheckConstraint('linked_entity_kind IS NULL) = (linked_entity_id IS NULL', name=op.f('ck_entity_events_linked_entity_together')),
    sa.PrimaryKeyConstraint('id', name=op.f('entity_events_pkey')),
    sa.UniqueConstraint('source', 'source_id', name=op.f('uq_entity_events_natural_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_entity_events_pm_entity_event_id'), 'entity_events', ['pm_entity_event_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_entity_events_entity_id'), 'entity_events', ['entity_id'], unique=False, schema='canonical')
    op.create_table('powermap_outbox',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('local_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('op', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('next_attempt_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_disposition', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('payload_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.CheckConstraint("op::text = ANY (ARRAY['CREATE'::character varying, 'UPDATE'::character varying, 'ENRICH'::character varying]::text[])", name=op.f('ck_powermap_outbox_op')),
    sa.CheckConstraint("status::text = ANY (ARRAY['PENDING'::character varying, 'DELIVERED'::character varying, 'REJECTED'::character varying, 'UNAVAILABLE'::character varying, 'SUPERSEDED'::character varying]::text[])", name=op.f('ck_powermap_outbox_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('powermap_outbox_pkey')),
    schema='sync'
    )
    op.create_index(op.f('uq_powermap_outbox_open'), 'powermap_outbox', ['entity_type', 'local_id'], unique=True, schema='sync', postgresql_where="((status)::text = 'PENDING'::text)")
    op.create_index(op.f('ix_powermap_outbox_due'), 'powermap_outbox', ['status', 'next_attempt_at'], unique=False, schema='sync')
    op.create_table('powermap_conditional_get_state',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('local_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('detail_etag', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('row_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('powermap_conditional_get_state_pkey')),
    sa.UniqueConstraint('entity_type', 'local_id', name=op.f('uq_powermap_conditional_get_state_row'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='sync'
    )
    op.create_table('organization_names',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('name_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('is_canonical', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('effective_start', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('effective_end', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('pm_org_name_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['canonical.organizations.id'], name=op.f('organization_names_organization_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('organization_names_pkey')),
    sa.UniqueConstraint('source', 'source_id', name=op.f('uq_organization_names_natural_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_organization_names_pm_org_name_id'), 'organization_names', ['pm_org_name_id'], unique=False, schema='canonical')
    op.create_index(op.f('ix_canonical_organization_names_organization_id'), 'organization_names', ['organization_id'], unique=False, schema='canonical')
    op.create_table('role_types',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pm_role_type_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('expects_jurisdiction', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('requires_qualifier', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('role_types_pkey')),
    sa.UniqueConstraint('slug', name=op.f('uq_role_types_slug'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='canonical'
    )
    op.create_index(op.f('ix_canonical_role_types_pm_role_type_id'), 'role_types', ['pm_role_type_id'], unique=False, schema='canonical')
    # ### end Alembic commands ###
