"""112 add powermap_nonconvergence_state

Revision ID: 73256e626f42
Revises: f1a2b3c4d5e6
Create Date: 2026-07-24 05:27:02.663410

"""
from collections.abc import Sequence

import sqlalchemy as sa

import clearinghouse_core.db.ulid
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '73256e626f42'
down_revision: str | Sequence[str] | None = 'f1a2b3c4d5e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('powermap_nonconvergence_state',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('local_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'local_id', name='uq_powermap_nonconvergence_state_row'),
    schema='sync'
    )
    op.create_index('ix_powermap_nonconvergence_state_count', 'powermap_nonconvergence_state', ['count'], unique=False, schema='sync')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_powermap_nonconvergence_state_count', table_name='powermap_nonconvergence_state', schema='sync')
    op.drop_table('powermap_nonconvergence_state', schema='sync')
    # ### end Alembic commands ###
