"""160 conditional-get state table

Revision ID: 890c046c6e58
Revises: e4a1c9b7d2f3
Create Date: 2026-08-06 02:41:59.291611

"""
from typing import Sequence, Union

import clearinghouse_core.db.ulid
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '890c046c6e58'
down_revision: Union[str, Sequence[str], None] = 'e4a1c9b7d2f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('powermap_conditional_get_state',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('local_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('detail_etag', sa.String(length=256), nullable=True),
    sa.Column('events_etag', sa.String(length=256), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'local_id', name='uq_powermap_conditional_get_state_row'),
    schema='sync'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('powermap_conditional_get_state', schema='sync')
    # ### end Alembic commands ###
