"""308 identity registry schema

Revision ID: 97e40a1f61ab
Revises: a1b2c3d4e5f6
Create Date: 2026-09-03 07:29:21.995354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import clearinghouse_core.db.ulid


# revision identifiers, used by Alembic.
revision: str = '97e40a1f61ab'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Each migration recreates its own schema (the #26 from-base replay rule).
    op.execute('CREATE SCHEMA IF NOT EXISTS "registry"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adjudications',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('subject_entity_id', clearinghouse_core.db.ulid.ULID(), nullable=True),
    sa.Column('target_entity_id', clearinghouse_core.db.ulid.ULID(), nullable=True),
    sa.Column('natural_key', sa.String(length=256), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='registry'
    )
    op.create_table('entities',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('merged_into', clearinghouse_core.db.ulid.ULID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merged_into'], ['registry.entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='registry'
    )
    op.create_index(op.f('ix_registry_entities_kind'), 'entities', ['kind'], unique=False, schema='registry')
    op.create_table('entity_keys',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('natural_key', sa.String(length=256), nullable=False),
    sa.Column('entity_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registered_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['registry.entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'natural_key', name='uq_registry_kind_natural_key'),
    schema='registry'
    )
    op.create_index(op.f('ix_registry_entity_keys_entity_id'), 'entity_keys', ['entity_id'], unique=False, schema='registry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registry_entity_keys_entity_id'), table_name='entity_keys', schema='registry')
    op.drop_table('entity_keys', schema='registry')
    op.drop_index(op.f('ix_registry_entities_kind'), table_name='entities', schema='registry')
    op.drop_table('entities', schema='registry')
    op.drop_table('adjudications', schema='registry')
    # ### end Alembic commands ###
    # Symmetric with upgrade (#302 CR): every schema-introducing migration in
    # this repo drops its schema on downgrade.
    op.execute('DROP SCHEMA IF EXISTS "registry" CASCADE')
