"""#108 add powermap_anchor_reanchor ledger

Revision ID: b3669b3ef3be
Revises: b3f7c2a9d4e1
Create Date: 2026-07-20 20:49:56.330701

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

import clearinghouse_core.db.ulid

# revision identifiers, used by Alembic.
revision: str = 'b3669b3ef3be'
down_revision: Union[str, Sequence[str], None] = 'b3f7c2a9d4e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('powermap_anchor_reanchor',
    sa.Column('id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('local_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('source_id', sa.String(length=512), nullable=True),
    sa.Column('old_pm_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('new_pm_id', clearinghouse_core.db.ulid.ULID(), nullable=False),
    sa.Column('disposition', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='sync'
    )
    op.create_index('ix_powermap_anchor_reanchor_old', 'powermap_anchor_reanchor', ['old_pm_id'], unique=False, schema='sync')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_powermap_anchor_reanchor_old', table_name='powermap_anchor_reanchor', schema='sync')
    op.drop_table('powermap_anchor_reanchor', schema='sync')
    # ### end Alembic commands ###
