"""#19 mirror PM EntityEvent fields on entity_events

Revision ID: f5f1bd9f84ae
Revises: b96aac248962
Create Date: 2026-06-17 22:09:55.483773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5f1bd9f84ae'
down_revision: Union[str, Sequence[str], None] = 'b96aac248962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_events', sa.Column('event_place_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='canonical')
    op.add_column('entity_events', sa.Column('notes', sa.Text(), nullable=True), schema='canonical')
    op.add_column('entity_events', sa.Column('verified_at', sa.Text(), nullable=True), schema='canonical')
    op.add_column('entity_events', sa.Column('pm_created_at', sa.Text(), nullable=True), schema='canonical')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_events', 'pm_created_at', schema='canonical')
    op.drop_column('entity_events', 'verified_at', schema='canonical')
    op.drop_column('entity_events', 'notes', schema='canonical')
    op.drop_column('entity_events', 'event_place_address', schema='canonical')
    # ### end Alembic commands ###
