-- Every published assignment names a role the dimension defines (#309 inc 4).
--
-- CR 77: this pins CONTAINMENT, not a fork. `roles` is generated by iterating
-- `assignments` through the same `role_for_span`, so the inclusion holds by
-- construction and this query cannot fail as long as that stays true — its job
-- is to notice if it stops being true (a filtered or re-derived roles model).
-- The fork worth detecting is ours drifting from the tier that already
-- publishes these keys to Power Map, and that needs an oracle dbt has no
-- session to reach: `parity_spans` diffs against `canonical.roles`.
select a.role_key, count(*) as n
from {{ ref('assignments') }} a
left join {{ ref('roles') }} r on r.role_key = a.role_key
where r.role_key is null
group by 1
