-- A published person's name is a NAME, or it is absent (#364).
--
-- The defect this exists for: `GetSponsors` returns a name-blanked STUB for a
-- superseded / departed (member, chamber-tenure) — a real `Id`, `Name` a single
-- space, no first/last. Survivorship read that as the member's newest
-- attestation, and Tina Orwall, Tim Sheldon, Robert Sutherland and Simon Sefzik
-- shipped `' '` as their legal name. Nothing here noticed; power-map#497 found
-- it a week later while building mapping models against `persons` — the
-- snapshot it read was `v20260903T085702Z`, the report came 2026-09-10 — and
-- under the #490 contract the producer owns a person's legal name — a consumer
-- applying that naively would have asserted whitespace as four names.
--
-- `conformed.entities._name` is why no blank is built today. This is the guard
-- that makes the next one a BUILD FAILURE here rather than a discovery
-- downstream, which is what the issue asked for.
--
-- Two predicates, because a blank and an edge are different shapes: `''` has no
-- characters to match, and everything else — `' '`, `'Marlo Braun '` (a real
-- WSL value, as is PDC's `'MICHAEL JAMES BAUMGARTNER '`) — is a name carrying
-- whitespace on an edge.
--
-- The edge test names the unicode SEPARATOR CLASS rather than enumerating
-- characters (CR 10), because enumerating them is a losing game. duckdb's
-- one-argument `trim` strips SPACES ONLY, so a tab-padded name walked past the
-- first cut of this gate (CR 2); spelling out space/tab/LF/CR then still missed
-- the NON-BREAKING SPACE, and NBSP padding is a routine text-extraction
-- artifact of a PDF — which the roster, one of the three name sources, is.
-- `[\pZ\s]` is RE2's separator class plus the ASCII whitespace: verified in
-- duckdb to flag NBSP-, space- and tab-padded values and to pass a clean one.
--
-- The point of matching Python's `str.strip()` — what `entities._name`
-- applies — is that a name it would have cleaned cannot come from the
-- survivorship at all. Such a row could only come from some OTHER writer into
-- `persons`, which is precisely the case a gate exists for; one blind to
-- everything but the defect already fixed upstream is not a guard.
--
-- NULL passes both edge tests: `NULL = ''` and `regexp_matches(NULL, …)` are
-- both NULL, which SQL drops. The pair check is where the null side is judged,
-- and it is spelled `is distinct from` rather than `<>` for the usual reason —
-- `NULL <> NULL` is NULL, so the plain form would be blind to exactly the rows
-- it exists to catch.
--
-- The pair travels together: a name with no source, or a source with no name,
-- is a survivorship bug even when neither value is blank.
--
-- GATED AT ZERO, with no baseline. The corpus is clean as of 2026-09-10 (3,135
-- persons), so any row here is new — unlike `assignments_seat_occupancy`, which
-- ratchets because its corpus was not clean on day one.
--
-- NOT expressed as a `not_null` column test on `name_full`, nor as a `required`
-- constraint in the published datapackage (the question #364 raises), because a
-- live entity CAN legitimately have no name. The instance that proved it —
-- WSL member 31656, Denny Heck, an ex-officio Senate Rules seat minted from the
-- retired `committee-members:` archive, registered and anchored in power-map
-- but attested by NO staging row at all — is gone: #366 merged him with the
-- roster identity his 1977-85 listings minted, and the merged entity is named
-- from that roster key. `parity_wsl.ACCEPTED` still carries the staging↔
-- canonical divergence for the same member; a registry merge does not touch it.
--
-- The SHAPE outlives the instance, which is why this stays a blank check rather
-- than becoming a null check: a registry entity no source attests is one
-- adjudication or one retired wire away at any time, and `required` would wedge
-- the nightly the day it recurs. Permitting a null costs this gate nothing.
--
-- Casts to varchar throughout: the hermetic build materializes `persons` empty,
-- and an empty object column can bind as something other than VARCHAR (#361).
--
-- Nothing here is hoisted into a jinja variable, for two reasons that both
-- bite. `test_persons_named` runs this file
-- with jinja stripped and refuses outright on any expression tag it does not
-- understand — deliberately, so the unit half can never quietly exercise a
-- mangled query; it knows `ref`, not a hand-rolled name. And dbt parses jinja
-- inside SQL COMMENTS too, so even naming the tag syntax here failed the whole
-- project's compile until this sentence stopped spelling it out.
select entity_id, name_full, name_source
from {{ ref('persons') }}
where cast(name_full as varchar) = ''
   or regexp_matches(cast(name_full as varchar), '^[\pZ\s]|[\pZ\s]$')
   or (cast(name_full as varchar) is null)
      is distinct from (cast(name_source as varchar) is null)
