"""Alembic migration environment — async PostgreSQL.

Generated by init-project-fastapi. Resolves the DB URL as DATABASE_URL_OWNER
(the DDL-owning role, set on the migrate host) → DATABASE_URL → alembic.ini's
sqlalchemy.url for offline tooling.

To extend with a custom type renderer (e.g. ULIDType → sa.String(26)),
define `render_item` and pass it to context.configure() in both
do_run_migrations and run_migrations_offline.
"""

import asyncio
import os
from logging.config import fileConfig

from sqlalchemy.ext.asyncio import create_async_engine

# Side-effect imports so every workspace member's tables register on Base.metadata
# before autogen runs. Add new domain packages here as they're created.
import clearinghouse_domain_legislative  # noqa: E402, F401
import clearinghouse_sync_powermap  # noqa: E402, F401
from alembic import context
from clearinghouse_core.models import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def get_url() -> str:
    """Read database URL from environment or alembic.ini.

    Prefers ``DATABASE_URL_OWNER`` (the DDL-owning role) when set so migrations
    run under ownership rights, falling back to ``DATABASE_URL`` for manual or
    pre-role-separation environments.
    """
    return (
        os.environ.get("DATABASE_URL_OWNER")
        or os.environ.get("DATABASE_URL")
        or config.get_main_option("sqlalchemy.url", "")
    )


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode — emit SQL without connecting."""
    context.configure(
        url=get_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_schemas=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection) -> None:
    """Run migrations using a sync connection."""
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        include_schemas=True,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Run migrations in 'online' mode — async connection."""
    connectable = create_async_engine(get_url())
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode — connect to the database."""
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
